"""baseline: topic_visibility + crew_applications

Revision ID: 0001_baseline
Revises: 
Create Date: 2026-06-28 21:51:27.153414

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0001_baseline'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # This baseline describes the schema that ALREADY exists in production (the
    # site shipped before Alembic was introduced, with the schema built by
    # db.create_all()). Create each table only if it's absent, so this migration
    # is a safe no-op on the live DB — letting `flask db upgrade` adopt it without
    # a manual `stamp` — while still building everything from scratch on a fresh
    # DB (CI, a new deploy). The real changes live in later migrations.
    bind = op.get_bind()
    existing = set(sa.inspect(bind).get_table_names())

    if 'crew_applications' not in existing:
        op.create_table('crew_applications',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('full_name', sa.String(length=160), nullable=False),
        sa.Column('email', sa.String(length=254), nullable=False),
        sa.Column('phone', sa.String(length=40), nullable=True),
        sa.Column('experience', sa.String(length=40), nullable=True),
        sa.Column('message', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id')
        )

    if 'topic_visibility' not in existing:
        op.create_table('topic_visibility',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('slug', sa.String(length=64), nullable=False),
        sa.Column('enabled', sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint('id')
        )
        with op.batch_alter_table('topic_visibility', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_topic_visibility_slug'), ['slug'], unique=True)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('topic_visibility', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_topic_visibility_slug'))

    op.drop_table('topic_visibility')
    op.drop_table('crew_applications')
    # ### end Alembic commands ###
